# Typical File for extension: vscode-graphql & CodeGen!
projects:
  default:
    schema:
      - http://localhost:8081/graphql
        # headers:
        #   Authorization: 'Bearer ${TOKEN}'
    documents:
      - '**/*.{gql, graphql}'
    extensions:
      endpoints:
        default:
          url: http://localhost:8081/graphql
      codegen:
        generates:
          # ./src/lib/graphql/schema.json:
          #   plugins:
          #     - introspection

          ./src/lib/graphql/_kitql/graphqlTypes.ts:
            plugins:
              - typescript
              - typescript-operations
              - typed-document-node
              - typescript-document-nodes

          ./src/lib/graphql/_kitql/graphqlStores.ts:
            plugins:
              - '@kitql/graphql-codegen'
            config:
              importBaseTypesFrom: $lib/graphql/_kitql/graphqlTypes
              operationPrefix: 'KQL_'

        config:
          useTypeImports: true
